services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pingthenest
      POSTGRES_PASSWORD: localdev
    ports:
      - "5481:5432"
  redis:
    image: redis:7
    ports:
      - "6381:6379"
