// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Section struct {
	ClassNbr            int32
	Subject             string
	CatalogNbr          string
	ClassSection        string
	Descr               pgtype.Text
	Term                string
	LastEnrollmentAvail pgtype.Int4
	UpdatedAt           pgtype.Timestamptz
}

type User struct {
	ID        int32
	Email     string
	Verified  pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type Watch struct {
	ID        int32
	UserID    pgtype.Int4
	ClassNbr  pgtype.Int4
	Active    pgtype.Bool
	CreatedAt pgtype.Timestamptz
}
