// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email) VALUES ($1) RETURNING id, email, verified, created_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const createWatch = `-- name: CreateWatch :one
INSERT INTO watches (user_id, class_nbr) VALUES ($1, $2) RETURNING id, user_id, class_nbr, active, created_at
`

type CreateWatchParams struct {
	UserID   pgtype.Int4
	ClassNbr pgtype.Int4
}

func (q *Queries) CreateWatch(ctx context.Context, arg CreateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, createWatch, arg.UserID, arg.ClassNbr)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClassNbr,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateWatch = `-- name: DeactivateWatch :exec
UPDATE watches
SET active = false
WHERE user_id = $1
  AND class_nbr = $2
`

type DeactivateWatchParams struct {
	UserID   pgtype.Int4
	ClassNbr pgtype.Int4
}

func (q *Queries) DeactivateWatch(ctx context.Context, arg DeactivateWatchParams) error {
	_, err := q.db.Exec(ctx, deactivateWatch, arg.UserID, arg.ClassNbr)
	return err
}

const getActiveWatchersForSection = `-- name: GetActiveWatchersForSection :many
SELECT
    u.id,
    u.email
FROM watches w
JOIN users u ON u.id = w.user_id
WHERE w.class_nbr = $1
  AND w.active = true
  AND u.verified = true
`

type GetActiveWatchersForSectionRow struct {
	ID    int32
	Email string
}

func (q *Queries) GetActiveWatchersForSection(ctx context.Context, classNbr pgtype.Int4) ([]GetActiveWatchersForSectionRow, error) {
	rows, err := q.db.Query(ctx, getActiveWatchersForSection, classNbr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveWatchersForSectionRow
	for rows.Next() {
		var i GetActiveWatchersForSectionRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctWatchedSubjects = `-- name: GetDistinctWatchedSubjects :many
SELECT DISTINCT s.subject FROM sections s
JOIN watches w ON w.class_nbr = s.class_nbr
WHERE w.active = true
`

func (q *Queries) GetDistinctWatchedSubjects(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctWatchedSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subject string
		if err := rows.Scan(&subject); err != nil {
			return nil, err
		}
		items = append(items, subject)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionLastAvail = `-- name: GetSectionLastAvail :one
SELECT last_enrollment_avail FROM sections WHERE class_nbr = $1
`

func (q *Queries) GetSectionLastAvail(ctx context.Context, classNbr int32) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getSectionLastAvail, classNbr)
	var last_enrollment_avail pgtype.Int4
	err := row.Scan(&last_enrollment_avail)
	return last_enrollment_avail, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, verified, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSection = `-- name: UpsertSection :exec
INSERT INTO sections (class_nbr, subject, catalog_nbr, class_section, descr, term, last_enrollment_avail)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (class_nbr) DO UPDATE SET last_enrollment_avail = $7, updated_at = now()
`

type UpsertSectionParams struct {
	ClassNbr            int32
	Subject             string
	CatalogNbr          string
	ClassSection        string
	Descr               pgtype.Text
	Term                string
	LastEnrollmentAvail pgtype.Int4
}

func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) error {
	_, err := q.db.Exec(ctx, upsertSection,
		arg.ClassNbr,
		arg.Subject,
		arg.CatalogNbr,
		arg.ClassSection,
		arg.Descr,
		arg.Term,
		arg.LastEnrollmentAvail,
	)
	return err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users SET verified = true WHERE id = $1
`

func (q *Queries) VerifyUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
