// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email) VALUES ($1) RETURNING id, email, verified, created_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO verification_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateVerificationTokenParams struct {
	Token     string
	UserID    pgtype.Int4
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createVerificationToken, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createWatch = `-- name: CreateWatch :one
INSERT INTO watches (user_id, class_nbr) VALUES ($1, $2) RETURNING id, user_id, class_nbr, active, created_at
`

type CreateWatchParams struct {
	UserID   pgtype.Int4
	ClassNbr pgtype.Int4
}

func (q *Queries) CreateWatch(ctx context.Context, arg CreateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, createWatch, arg.UserID, arg.ClassNbr)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClassNbr,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateWatch = `-- name: DeactivateWatch :exec
UPDATE watches
SET active = false
WHERE user_id = $1
  AND class_nbr = $2
`

type DeactivateWatchParams struct {
	UserID   pgtype.Int4
	ClassNbr pgtype.Int4
}

func (q *Queries) DeactivateWatch(ctx context.Context, arg DeactivateWatchParams) error {
	_, err := q.db.Exec(ctx, deactivateWatch, arg.UserID, arg.ClassNbr)
	return err
}

const deleteWatchByUserAndClass = `-- name: DeleteWatchByUserAndClass :exec
DELETE FROM watches
WHERE user_id = (SELECT id FROM users WHERE email = $1)
  AND class_nbr = $2
`

type DeleteWatchByUserAndClassParams struct {
	Email    string
	ClassNbr pgtype.Int4
}

func (q *Queries) DeleteWatchByUserAndClass(ctx context.Context, arg DeleteWatchByUserAndClassParams) error {
	_, err := q.db.Exec(ctx, deleteWatchByUserAndClass, arg.Email, arg.ClassNbr)
	return err
}

const getActiveWatchersForSection = `-- name: GetActiveWatchersForSection :many
SELECT
    u.id,
    u.email
FROM watches w
JOIN users u ON u.id = w.user_id
WHERE w.class_nbr = $1
  AND w.active = true
  AND u.verified = true
`

type GetActiveWatchersForSectionRow struct {
	ID    int32
	Email string
}

func (q *Queries) GetActiveWatchersForSection(ctx context.Context, classNbr pgtype.Int4) ([]GetActiveWatchersForSectionRow, error) {
	rows, err := q.db.Query(ctx, getActiveWatchersForSection, classNbr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveWatchersForSectionRow
	for rows.Next() {
		var i GetActiveWatchersForSectionRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctWatchedSubjects = `-- name: GetDistinctWatchedSubjects :many
SELECT DISTINCT s.subject FROM sections s
JOIN watches w ON w.class_nbr = s.class_nbr
WHERE w.active = true
`

func (q *Queries) GetDistinctWatchedSubjects(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctWatchedSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subject string
		if err := rows.Scan(&subject); err != nil {
			return nil, err
		}
		items = append(items, subject)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionByClassNbr = `-- name: GetSectionByClassNbr :one
SELECT class_nbr, subject, catalog_nbr, class_section, descr, term, last_enrollment_avail, updated_at FROM sections WHERE class_nbr = $1
`

func (q *Queries) GetSectionByClassNbr(ctx context.Context, classNbr int32) (Section, error) {
	row := q.db.QueryRow(ctx, getSectionByClassNbr, classNbr)
	var i Section
	err := row.Scan(
		&i.ClassNbr,
		&i.Subject,
		&i.CatalogNbr,
		&i.ClassSection,
		&i.Descr,
		&i.Term,
		&i.LastEnrollmentAvail,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionLastAvail = `-- name: GetSectionLastAvail :one
SELECT last_enrollment_avail FROM sections WHERE class_nbr = $1
`

func (q *Queries) GetSectionLastAvail(ctx context.Context, classNbr int32) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getSectionLastAvail, classNbr)
	var last_enrollment_avail pgtype.Int4
	err := row.Scan(&last_enrollment_avail)
	return last_enrollment_avail, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, verified, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, verified, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT token, user_id, expires_at, used, created_at FROM verification_tokens WHERE token = $1
`

func (q *Queries) GetVerificationToken(ctx context.Context, token string) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, token)
	var i VerificationToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getWatchesForEmail = `-- name: GetWatchesForEmail :many
SELECT w.id, w.class_nbr, w.active, w.created_at,
       s.subject, s.catalog_nbr, s.class_section, s.descr, s.last_enrollment_avail
FROM watches w
JOIN users u ON u.id = w.user_id
JOIN sections s ON s.class_nbr = w.class_nbr
WHERE u.email = $1
ORDER BY w.created_at DESC
`

type GetWatchesForEmailRow struct {
	ID                  int32
	ClassNbr            pgtype.Int4
	Active              pgtype.Bool
	CreatedAt           pgtype.Timestamptz
	Subject             string
	CatalogNbr          string
	ClassSection        string
	Descr               pgtype.Text
	LastEnrollmentAvail pgtype.Int4
}

func (q *Queries) GetWatchesForEmail(ctx context.Context, email string) ([]GetWatchesForEmailRow, error) {
	rows, err := q.db.Query(ctx, getWatchesForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWatchesForEmailRow
	for rows.Next() {
		var i GetWatchesForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassNbr,
			&i.Active,
			&i.CreatedAt,
			&i.Subject,
			&i.CatalogNbr,
			&i.ClassSection,
			&i.Descr,
			&i.LastEnrollmentAvail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE verification_tokens SET used = true WHERE token = $1
`

func (q *Queries) MarkTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markTokenUsed, token)
	return err
}

const upsertSection = `-- name: UpsertSection :exec
INSERT INTO sections (class_nbr, subject, catalog_nbr, class_section, descr, term, last_enrollment_avail)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (class_nbr) DO UPDATE SET last_enrollment_avail = $7, updated_at = now()
`

type UpsertSectionParams struct {
	ClassNbr            int32
	Subject             string
	CatalogNbr          string
	ClassSection        string
	Descr               pgtype.Text
	Term                string
	LastEnrollmentAvail pgtype.Int4
}

func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) error {
	_, err := q.db.Exec(ctx, upsertSection,
		arg.ClassNbr,
		arg.Subject,
		arg.CatalogNbr,
		arg.ClassSection,
		arg.Descr,
		arg.Term,
		arg.LastEnrollmentAvail,
	)
	return err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users SET verified = true WHERE id = $1
`

func (q *Queries) VerifyUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
